name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "20.14.0"

    - name: Hexo Generate
      run: |
        rm -f node_modules
        npm install
        rm -rf ./public
        npm run clean
        npm run build